import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">HomePage</Link>
        </li>
        <li>
          <Link to="/product">Product</Link>
        </li>
        <li>
          <Link to="/shoppage">ShopPage</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/contactus">Contactus</Link>
        </li>
        <li>
          <Link to="/payment">Payment</Link>
        </li>
        <li>
          <Link to="/useraccount">Useraccount</Link>
        </li>
        <li>
          <Link to="/pricacypolicy">Pricacypolicy</Link>
        </li>
        <li>
          <Link to="/returnrefund">Returnrefund</Link>
        </li>
        <li>
          <Link to="/tc">TC</Link>
        </li>
        <li>
          <Link to="/orderplacedpage">Orderplacedpage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
